# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      # Check if code compiles
      - id: cargo-check
        name: cargo check
        entry: cargo check
        language: system
        types: [rust]
        pass_filenames: false
        always_run: true

      # Format code with rustfmt
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --check
        language: system
        types: [rust]
        pass_filenames: false
        always_run: true

      # Lint with clippy
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
        always_run: true

      # Run tests
      - id: cargo-test
        name: cargo test
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false
        always_run: true

      
      # Security audit
      - id: cargo-audit
        name: cargo audit
        entry: cargo audit
        language: system
        types: [rust]
        pass_filenames: false
        always_run: true

      # Check documentation
      - id: cargo-doc
        name: cargo doc
        entry: cargo doc --no-deps
        language: system
        types: [rust]
        pass_filenames: false
        always_run: true