[package]
name = "cc-switch"
version = "0.0.15"
edition = "2024"
description = "A CLI tool for managing multiple Claude API configurations and automatically switching between them"
license = "MIT"
repository = "https://github.com/jingzhao/cc_auto_switch"
homepage = "https://github.com/jingzhao/cc_auto_switch"
documentation = "https://github.com/jingzhao/cc_auto_switch"
keywords = ["claude", "api", "configuration", "cli"]
categories = ["command-line-utilities"]

[[bin]]
name = "cc-switch"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.43", features = ["derive", "cargo"] }
clap_complete = "4.5.55"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
dirs = "6.0.0"
tempfile = "3.20.0"
colored = "3.0"
crossterm = "0.29.0"

[package.metadata.docs.rs]
all-features = true
