[package]
name = "cc-switch"
version = "0.0.5"
edition = "2024"
description = "A CLI tool for managing multiple Claude API configurations and automatically switching between them"
license = "MIT"
repository = "https://github.com/jingzhao/cc_auto_switch"
homepage = "https://github.com/jingzhao/cc_auto_switch"
documentation = "https://github.com/jingzhao/cc_auto_switch"
keywords = ["claude", "api", "configuration", "cli"]
categories = ["command-line-utilities"]

[[bin]]
name = "cc-switch"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.42", features = ["derive", "cargo"] }
clap_complete = "4.5.42"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "6.0.0"
tempfile = "3.16"

[package.metadata.docs.rs]
all-features = true
