[package]
name = "cc-switch"
version = "0.0.36"
edition = "2024"
description = "A CLI tool for managing multiple Claude API configurations and automatically switching between them"
license = "MIT"
repository = "https://github.com/Linuxdazhao/cc_auto_switch"
homepage = "https://github.com/Linuxdazhao/cc_auto_switch"
documentation = "https://github.com/Linuxdazhao/cc_auto_switch"
keywords = ["claude", "api", "configuration", "cli"]
categories = ["command-line-utilities"]

[[bin]]
name = "cc-switch"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.43", features = ["derive", "cargo"] }
clap_complete = "4.5.55"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0"
dirs = "6.0.0"
tempfile = "3.20.0"
colored = "3.0"
crossterm = "0.29.0"

[package.metadata.docs.rs]
all-features = true

[profile.dev]
incremental = true # 以较小的步骤编译您的二进制文件。

[profile.release]
codegen-units = 1 # 允许 LLVM 执行更好的优化。
lto = true        # 启用链接时优化。
opt-level = "s"   # 优先考虑小的二进制文件大小。如果您更喜欢速度，请使用 `3`。
panic = "abort"   # 通过禁用 panic 处理程序来提高性能。
strip = true      # 确保移除调试符号。
