# Cross-compilation configuration for aarch64-unknown-linux-gnu target
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

# GitHub Packages registry configuration
[registries.github]
index = "sparse+https://github.com/jingzhao/cc_auto_switch/index/"